name: port-au-next
services:
  # Shared PostgreSQL database
  postgres:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - port_au_next_network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - deployment-manager
    networks:
      - port_au_next_network
  
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - port_au_next_network

  thumbor:
    image: minimalcompact/thumbor:6.7.5
    restart: always
    environment:
      SECURITY_KEY: ${THUMBOR_SECURITY_KEY}
    volumes:
      - thumbor_data:/data
    networks:
      - port_au_next_network

  # Deployment managerr
  deployment-manager:
    build:
      context: ./deployment-manager
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./apps:/app/apps:rw
      - ./deployment-manager/public:/app/public:ro
      - ~/.ssh/id_rsa:/home/nextjs/.ssh/id_rsa:ro
      - ~/.ssh/id_rsa.pub:/home/nextjs/.ssh/id_rsa.pub:ro
      - ./nginx:/app/nginx:rw
      - ./docker-compose.yml:/app/docker-compose.yml:ro
    environment:
      - NODE_ENV=production
      - PORT=3000
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - THUMBOR_SECURITY_KEY=${THUMBOR_SECURITY_KEY}
      - HOST_APPS_DIR=/app/apps
      - CLOUDFLARE_API_EMAIL=${CLOUDFLARE_API_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - port_au_next_network

networks:
  port_au_next_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  thumbor_data:
  nginx_cache: